# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/kltexx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter klte klteacg klteatt kltecan kltelra kltetmo klteub klteusc kltevzw kltedv kltespr kltekor kltektt kltelgt klteskt kltevzw klteactivexx klteattactive kltechnduo klteduos,$(TARGET_DEVICE)),)

endif
