# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/klte-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter klte klteactivexx kltechn kltedv kltekdi kltekor kltespr kltesprsports klteusc kltevzw,$(TARGET_DEVICE)),)

endif
